# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Python 3.12
        uses: actions/setup-python@v5.5.0
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install -r requirements_test.txt
          pip install -e .
      - name: Lint with flake8
        run: |
          flake8 voluptuous_openapi
      - name: Test with pytest
        run: |
          pytest tests
      - name: Check formatting with black
        run: |
          black voluptuous_openapi tests --check
